### Upload video
POST http://localhost:8090/api/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="<filename>"
Content-Type: application/octet-stream

< /home/doston/Videos/<filename>
--WebAppBoundary--

### Open video
GET http://localhost:8090/api/attach/open/<attachId>
Accept: video/*

### Download video
GET http://localhost:8090/api/attach/download/<attachId>
Accept: application/octet-stream

### Get all videos with pagination (Admin)
GET http://localhost:8090/api/attach?size=10&page=1
Accept: application/json
Authorization: Bearer token

### Delete video (Admin)
DELETE http://localhost:8090/api/attach/<attachId>
Authorization: Bearer token
