### Upload video
POST http://localhost:8090/api/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="<filename>"
Content-Type: application/octet-stream

< /home/doston/Videos/<filename>
--WebAppBoundary--

### Open video
GET http://localhost:8090/api/attach/open/<attachId>
Accept: video/*

### Download video
GET http://localhost:8090/api/attach/download/<attachId>
Accept: application/octet-stream

### Get all videos with pagination (Admin)
GET http://localhost:8090/api/attach?size=10&page=1
Accept: application/json
Authorization: Bearer token

### Delete video (Admin)
DELETE http://localhost:8090/api/attach/<attachId>
Authorization: Bearer token

### streaming just for fun(only applicable for .mp4)

### Stream Video with Range Header (Partial Content)
GET http://localhost:8090/api/attach/stream/b76da40b-1680-402f-9c1b-ab3f890f7048.mp4
Range: bytes=0-1000000

### Stream Video without Range Header (Full Content)
GET http://localhost:8090/api/attach/stream/b76da40b-1680-402f-9c1b-ab3f890f7048.mp4

### Stream Video with Specific Range
GET http://localhost:8090/api/attach/stream/b76da40b-1680-402f-9c1b-ab3f890f7048.mp4
Range: bytes=5000000-10000000