### Register new account
POST http://localhost:8090/api/auth/registration
Content-Type: application/json
Accept-Language: ru

{
  "name": "<name>",
  "surname": "<surname>",
  "email": "<email>",
  "password": "<password>"
}

### Registration confirmation (code in Integer)
POST http://localhost:8090/api/auth/registration/confirm
Content-Type: application/json
Accept-Language: en

{
  "email": "<email>",
  "code": 111111
}

### Login
POST http://localhost:8090/api/auth/login
Content-Type: application/json
Accept-Language: uz

{
  "email": "<email>",
  "password": "<password>"
}

### Refresh token
POST http://localhost:8090/api/auth/refresh
Content-Type: application/json
Accept-Language: ru

{
    "refreshToken": "<refreshToken>"
}