### Create new category
POST http://localhost:8090/api/category
Content-Type: application/json
Authorization: Bearer token

{
    "name": "<category name>"
}

### Update category by id
PUT http://localhost:8090/api/category/<category id>
Content-Type: application/json
Authorization: Bearer token

{
    "name": "< new category name >"
}

### Delete category by id (Admin)
DELETE http://localhost:8090/api/category/<category id>
Authorization: Bearer token

### Get category list with pagination (Admin)
GET http://localhost:8090/api/category?size=10&page=1
Accept: application/json
Authorization: Bearer token