### Add new channel
POST http://localhost:8090/api/channels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibG9naW4iOiJoZWxsb0BzYWxvbS5jb20iLCJzdWIiOiJoZWxsb0BzYWxvbS5jb20iLCJpYXQiOjE3MzIyMjQwOTksImV4cCI6MTczMjgyODg5OX0.uJCIvuq24lh9WldZacitrXTVTzlHnZTfnMYfhMSOzlA

{
    "name": "Better ideas",
    "description": "We will help people help others",
    "handle": "better_ideas"
}

### Get channel by id
GET http://localhost:8090/api/channels/channel?id=f2513e56-1bdb-4120-8b45-83123509487b
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibG9naW4iOiJoZWxsb0BzYWxvbS5jb20iLCJzdWIiOiJoZWxsb0BzYWxvbS5jb20iLCJpYXQiOjE3MzIyMjQwOTksImV4cCI6MTczMjgyODg5OX0.uJCIvuq24lh9WldZacitrXTVTzlHnZTfnMYfhMSOzlA
