### Add new channel
POST http://localhost:8090/api/channels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibG9naW4iOiJoZWxsb0BzYWxvbS5jb20iLCJzdWIiOiJoZWxsb0BzYWxvbS5jb20iLCJpYXQiOjE3MzIyOTE3NDUsImV4cCI6MTczMjg5NjU0NX0.JeK8LFIjtTUTujtitG3rsEd5urE9hTZsvYjR_n2yXXQ
Accept-Language: ru

{
    "name": "Buyuk insonlar",
    "description": "We will help people help others",
    "handle": "updated_handle2"
}

### Update channel info by id
PATCH http://localhost:8090/api/channels/edit-info?id=1c5da01e-184d-430d-aff9-07ca4d3fa028
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibG9naW4iOiJoZWxsb0BzYWxvbS5jb20iLCJzdWIiOiJoZWxsb0BzYWxvbS5jb20iLCJpYXQiOjE3MzIyOTE3NDUsImV4cCI6MTczMjg5NjU0NX0.JeK8LFIjtTUTujtitG3rsEd5urE9hTZsvYjR_n2yXXQ
Accept-Language: ru

{
  "name": "Updated name",
  "description": "Updated description",
  "handle": "updated_handle2"
}

### Update channel photo by id
PATCH http://localhost:8090/api/channels/edit-photo?id=1c5da01e-184d-430d-aff9-07ca4d3fa028
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibG9naW4iOiJoZWxsb0BzYWxvbS5jb20iLCJzdWIiOiJoZWxsb0BzYWxvbS5jb20iLCJpYXQiOjE3MzIyOTE3NDUsImV4cCI6MTczMjg5NjU0NX0.JeK8LFIjtTUTujtitG3rsEd5urE9hTZsvYjR_n2yXXQ
Accept-Language: ru

{
    "photoId": "6af9e57d-fc8e-4ce5-bf26-820e49fac223.png"
}

### Update channel banner by id
PATCH http://localhost:8090/api/channels/edit-banner?id=1c5da01e-184d-430d-aff9-07ca4d3fa028
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibG9naW4iOiJoZWxsb0BzYWxvbS5jb20iLCJzdWIiOiJoZWxsb0BzYWxvbS5jb20iLCJpYXQiOjE3MzIyOTE3NDUsImV4cCI6MTczMjg5NjU0NX0.JeK8LFIjtTUTujtitG3rsEd5urE9hTZsvYjR_n2yXXQ
Accept-Language: ru

{
    "bannerId": "d0e2b439-4ad2-4faa-81b9-ec5c66f2928f.jpeg"
}

### Get channel by id
GET http://localhost:8090/api/channels/id?id=f2513e56-1bdb-4120-8b45-83123509487b
Accept: application/json

### Get channel by name
GET http://localhost:8090/api/channels/name?name=inson
Accept: application/json

### Get channel by handle
GET http://localhost:8090/api/channels/handle?handle=t
Accept: application/json