### Create a new comment
POST http://localhost:8090/api/comments
Content-Type: application/json
Authorization: Bearer token

{
  "content": "<content>",
  "videoId": "<videoId>",
  "replyId": "<reply_id(can be null)>"
}

### Update comment by commentId
PATCH http://localhost:8090/api/comments
Content-Type: application/json
Authorization: Bearer token

{
  "content": "<content>"
}

### Delete comment by ID
DELETE http://localhost:8090/api/comments/<id>
Content-Type: application/json
Authorization: Bearer token

### Get all comments (admin)
GET http://localhost:8090/api/comments/admin/list
Content-Type: application/json
Authorization: Bearer token

### Get all comments by profileId (admin)
GET http://localhost:8090/api/comments/admin/list/profile?profileId=<id>
Content-Type: application/json
Authorization: Bearer token

### Get all comments by videoId
GET http://localhost:8090/api/comments/video/<videoId>
Content-Type: application/json