### Create Playlist
POST http://localhost:8090/playlist/create
Content-Type: application/json
Authorization: Bearer token

{
  "channelId": "<channel_id>",
  "name": "<name>",
  "description": "<description>",
  "status": "<status>",
  "orderNumber": 0
}

### Update Playlist
PUT http://localhost:8090/playlist/update/<playlist_id>
Content-Type: application/json
Authorization: Bearer token

{
  "name": "<name>",
  "description": "<description>",
  "status": "<status>",
  "orderNumber": 0
}

### Change Status
PUT http://localhost:8090/playlist/change-status
Content-Type: application/json
Authorization: token

{
  "playlistId": "",
  "status": "PRIVATE"
}

### Delete Playlist
DELETE http://localhost:8090/profile/delete/<playlist-id>
Content-Type: application/json
Authorization: Bearer token

### Get Pagination for Admin
GET http://localhost:8090/playlist/get-pagination-admin?page=<>&size=<>
Authorization: Bearer token

### Get Pagination for User
GET http://localhost:8090/playlist/get-pagination-user?page<>&size=<>

### Get Channel Playlists
GET http://localhost:8090/playlist/get-channel-playlist/<channel_id>

### Get Playlist Basic Info
GET http://localhost:8090/playlist/get-playlist-basic-info/<playlist_id>