### Change Password
POST http://localhost:8090/profile/changePassword
Content-Type: application/json
Authorization: Bearer token

{
    "oldPassword": "<oldPassword>",
    "newPassword": "<newPassword>"
}

### Get all profiles
GET http://localhost:8090/profile/getAll
Accept: application/json
Authorization: Bearer token

### Update Email
PUT localhost:8090/profile/updateEmail?email=<email>
Authorization: Bearer token

### Confirm Email
GET http://localhost:8090/profile/confirm/<code>
Authorization: Bearer token
