### Create new video
POST http://localhost:8090/api/videos
Content-Type: application/json
Authorization: Bearer token

{
  "title": "<Video title>",
  "description": "<Video description>",
  "categoryId": 1,
  "attachId": "<new uploaded attach video id>",
  "previewAttachId": "<new uploaded preview id>",
  "type": "<type>",
  "status": "<status>"
}

### Watch video by id
GET http://localhost:8090/api/videos/watch?v=<video id>
Accept: application/json
Authorization: Bearer token


### Get videos by categoryId (pagination)
GET http://localhost:8090/api/videos/category?categoryId=<categoryId>
Accept: application/json

### Get videos by title (pagination)
GET http://localhost:8090/api/videos/title?title=<title(no need for to be full)>
Accept: application/json

### Update video details
PUT http://localhost:8090/api/videos/<video id>
Content-Type: application/json
Authorization: Bearer token

{
  "title": "<Updated title>",
  "description": "<Updated description>",
  "categoryId": 2,
  "playlistId": "<playlist id>",
  "previewAttachId": "<updated preview id>",
  "type": "<updated type>",
  "status": "<updated status>"
}

### Update video status
PATCH http://localhost:8090/api/videos/<video id>/status
Content-Type: application/json
Authorization: Bearer token

{
  "status": "PUBLIC"
}

### Update video playlist
PATCH http://localhost:8090/api/videos/<video id>/playlist
Content-Type: application/json
Authorization: Bearer token

{
  "playlistId": "<new playlist id>"
}

### Update video category
PATCH http://localhost:8090/api/videos/<video id>/category
Content-Type: application/json
Authorization: Bearer token

{
  "categoryId": 3
}

### Update video preview
PATCH http://localhost:8090/api/videos/<video id>/preview
Content-Type: application/json
Authorization: Bearer token

{
  "previewAttachId": "<new preview attach id>"
}