### Create new video
POST http://localhost:8090/api/videos
Content-Type: application/json
Authorization: Bearer token

{
  "title": "<Video title>",
  "description": "<Video description>",
  "categoryId": 1,
  "attachId": "<new uploaded attach video id>",
  "previewAttachId": "<new uploaded preview id>",
  "type": "<type>",
  "status": "<status>"
}

### Watch video by id
GET http://localhost:8090/api/videos/watch?v=<video id>
Accept: application/json
Authorization: Bearer token


### Get videos by categoryId (pagination)
GET http://localhost:8090/api/videos/category?categoryId=<categoryId>
Accept: application/json

### Get videos by title (pagination)
GET http://localhost:8090/api/videos/title?title=<title(no need for to be full)>
Accept: application/json

### Get videos by channelId (pagination)
GET http://localhost:8090/api/videos/channel/<channelId>?page=2&size=4
Accept: application/json

### Get all videos list (pagination) (admin)
GET http://localhost:8090/api/videos?page=1&size=4
Accept: application/json
Authorization:  Bearer token(admin)

### 10. Get partial video info by videoId
GET http://localhost:8090/api/videos/edit?v=<videoId>
Accept: application/json
Authorization: Bearer token


### Update video details
PUT http://localhost:8090/api/videos/<video id>
Content-Type: application/json
Authorization: Bearer token

{
  "The result of '10. Get partial video info by videoId' should be put here": "run 10. with video id then delete updated date"

}

### Update video status
PATCH http://localhost:8090/api/videos/<video id>/status
Content-Type: application/json
Authorization: Bearer token

{
  "status": "PUBLIC"
}

### Update video playlist
PATCH http://localhost:8090/api/videos/<video id>/playlist
Content-Type: application/json
Authorization: Bearer token

{
  "playlistId": "<new playlist id>"
}

### Update video category
PATCH http://localhost:8090/api/videos/<video id>/category
Content-Type: application/json
Authorization: Bearer token

{
  "categoryId": 3
}

### Update video preview
PATCH http://localhost:8090/api/videos/<video id>/preview
Content-Type: application/json
Authorization: Bearer token

{
  "previewAttachId": "<new preview attach id>"
}

### Share video
POST http://localhost:8090/api/videos/<video_id>/share
Content-Type: application/json
Authorization: Bearer token


